version: '3.8'

services:
  api:
    build: .
    container_name: mnist-api
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    command: python api.py
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  web:
    build: .
    container_name: mnist-web
    ports:
      - "7860:7860"
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    command: python app.py
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped

  train:
    build: .
    container_name: mnist-train
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    command: python train.py --model both --epochs 10
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - training