version: '3.8'

services:
  # FastAPI backend service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: mnist-api
    ports:
      - "8000:8000"
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - mnist-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js frontend service (NEW)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mnist-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - mnist-network

  # Original Gradio web interface (optional)
  gradio:
    build: .
    container_name: mnist-gradio
    ports:
      - "7860:7860"
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    command: python app.py
    environment:
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    restart: unless-stopped
    networks:
      - mnist-network
    profiles:
      - gradio  # Only runs when explicitly requested

  # Training service
  train:
    build: .
    container_name: mnist-train
    volumes:
      - ./outputs:/app/outputs
      - ./data:/app/data
    command: python train.py --model both --epochs 10
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - mnist-network
    profiles:
      - training

networks:
  mnist-network:
    driver: bridge