services:
  - type: web
    name: mnist-classifier-api
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /
    # Increase health check timeout for model loading
    healthCheckInterval: 30s
    healthCheckTimeout: 10s
    healthCheckFailureThreshold: 5
